apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-security-policy
  namespace: default
spec:
  selector:
    matchLabels:
      app: wisecow

  process:
    # Block specific dangerous commands
    matchPaths:
      - path: /bin/ls
        action: Block
      - path: /usr/bin/ls  
        action: Block
      - path: /bin/pwd
        action: Block
      - path: /usr/bin/pwd
        action: Block
      - path: /usr/bin/wget
        action: Block
      - path: /usr/bin/curl
        action: Block
      - path: /usr/bin/whoami
        action: Block
      - path: /usr/bin/id
        action: Block

  # Default action: Allow everything else
  action: Allow