apiVersion: kubearmor.io/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-wisecow-zero-trust
  namespace: default 
spec:
  selector:
    matchLabels:
      app: wisecow

  process:
    # The action is to allow these paths. All others will be blocked by default.
    matchPaths:
    - path: /bin/bash
    - path: /bin/cat
    - path: /bin/rm
    - path: /bin/sleep
    - path: /usr/bin/mkfifo
    - path: /usr/bin/nc
    - path: /usr/bin/command
    - path: /usr/games/cowsay
    - path: /usr/games/fortune
    - path: /app/wisecow.sh

  # Allow only the necessary file access
  file:
    matchPaths:
    - path: /app/response
    - path: /usr/share/cowsay/cows/ 
      readOnly: true
    - path: /usr/share/games/fortunes/ 
      readOnly: true

  action: Block